apiVersion: apps/v1
kind: Deployment
metadata:
  name: fx-webform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fx-webform
  template:
    metadata:
      labels:
        app: fx-webform
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: fx-webform
        image: crazk8scj7ur4lzvcryvdkv4.azurecr.io/modernise/fx-webforms:dummy
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fx-webform
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: fx-webform
